// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flights.proto

package flights

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BookReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookReq) Reset()         { *m = BookReq{} }
func (m *BookReq) String() string { return proto.CompactTextString(m) }
func (*BookReq) ProtoMessage()    {}
func (*BookReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_abcf183ae4a14dc1, []int{0}
}

func (m *BookReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookReq.Unmarshal(m, b)
}
func (m *BookReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookReq.Marshal(b, m, deterministic)
}
func (m *BookReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookReq.Merge(m, src)
}
func (m *BookReq) XXX_Size() int {
	return xxx_messageInfo_BookReq.Size(m)
}
func (m *BookReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BookReq.DiscardUnknown(m)
}

var xxx_messageInfo_BookReq proto.InternalMessageInfo

type BookReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookReply) Reset()         { *m = BookReply{} }
func (m *BookReply) String() string { return proto.CompactTextString(m) }
func (*BookReply) ProtoMessage()    {}
func (*BookReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_abcf183ae4a14dc1, []int{1}
}

func (m *BookReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookReply.Unmarshal(m, b)
}
func (m *BookReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookReply.Marshal(b, m, deterministic)
}
func (m *BookReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookReply.Merge(m, src)
}
func (m *BookReply) XXX_Size() int {
	return xxx_messageInfo_BookReply.Size(m)
}
func (m *BookReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BookReply.DiscardUnknown(m)
}

var xxx_messageInfo_BookReply proto.InternalMessageInfo

type CancelReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelReq) Reset()         { *m = CancelReq{} }
func (m *CancelReq) String() string { return proto.CompactTextString(m) }
func (*CancelReq) ProtoMessage()    {}
func (*CancelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_abcf183ae4a14dc1, []int{2}
}

func (m *CancelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelReq.Unmarshal(m, b)
}
func (m *CancelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelReq.Marshal(b, m, deterministic)
}
func (m *CancelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelReq.Merge(m, src)
}
func (m *CancelReq) XXX_Size() int {
	return xxx_messageInfo_CancelReq.Size(m)
}
func (m *CancelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelReq.DiscardUnknown(m)
}

var xxx_messageInfo_CancelReq proto.InternalMessageInfo

type CancelReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelReply) Reset()         { *m = CancelReply{} }
func (m *CancelReply) String() string { return proto.CompactTextString(m) }
func (*CancelReply) ProtoMessage()    {}
func (*CancelReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_abcf183ae4a14dc1, []int{3}
}

func (m *CancelReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelReply.Unmarshal(m, b)
}
func (m *CancelReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelReply.Marshal(b, m, deterministic)
}
func (m *CancelReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelReply.Merge(m, src)
}
func (m *CancelReply) XXX_Size() int {
	return xxx_messageInfo_CancelReply.Size(m)
}
func (m *CancelReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelReply.DiscardUnknown(m)
}

var xxx_messageInfo_CancelReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*BookReq)(nil), "flights.BookReq")
	proto.RegisterType((*BookReply)(nil), "flights.BookReply")
	proto.RegisterType((*CancelReq)(nil), "flights.CancelReq")
	proto.RegisterType((*CancelReply)(nil), "flights.CancelReply")
}

func init() { proto.RegisterFile("flights.proto", fileDescriptor_abcf183ae4a14dc1) }

var fileDescriptor_abcf183ae4a14dc1 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xcb, 0xc9, 0x4c,
	0xcf, 0x28, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x38, 0xb9,
	0xd8, 0x9d, 0xf2, 0xf3, 0xb3, 0x83, 0x52, 0x0b, 0x95, 0xb8, 0xb9, 0x38, 0x21, 0xcc, 0x82, 0x9c,
	0x4a, 0x10, 0xc7, 0x39, 0x31, 0x2f, 0x39, 0x35, 0x07, 0x24, 0xc3, 0xcb, 0xc5, 0x0d, 0xe3, 0x14,
	0xe4, 0x54, 0x1a, 0x15, 0x72, 0xb1, 0xbb, 0x41, 0xb4, 0x0b, 0xe9, 0x43, 0xb5, 0x07, 0x38, 0x0b,
	0x09, 0xe8, 0xc1, 0xac, 0x80, 0x1a, 0x28, 0x25, 0x84, 0x26, 0x52, 0x90, 0x53, 0x29, 0x64, 0x0a,
	0x37, 0x37, 0xc0, 0x59, 0x08, 0xa1, 0x00, 0x6e, 0x97, 0x94, 0x08, 0x86, 0x58, 0x41, 0x4e, 0x65,
	0x12, 0x1b, 0xd8, 0xd9, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x28, 0xb4, 0x73, 0xc7,
	0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FlightsClient is the client API for Flights service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FlightsClient interface {
	BookRPC(ctx context.Context, in *BookReq, opts ...grpc.CallOption) (*BookReply, error)
	CancelRPC(ctx context.Context, in *CancelReq, opts ...grpc.CallOption) (*CancelReply, error)
}

type flightsClient struct {
	cc *grpc.ClientConn
}

func NewFlightsClient(cc *grpc.ClientConn) FlightsClient {
	return &flightsClient{cc}
}

func (c *flightsClient) BookRPC(ctx context.Context, in *BookReq, opts ...grpc.CallOption) (*BookReply, error) {
	out := new(BookReply)
	err := c.cc.Invoke(ctx, "/flights.Flights/BookRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightsClient) CancelRPC(ctx context.Context, in *CancelReq, opts ...grpc.CallOption) (*CancelReply, error) {
	out := new(CancelReply)
	err := c.cc.Invoke(ctx, "/flights.Flights/CancelRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlightsServer is the server API for Flights service.
type FlightsServer interface {
	BookRPC(context.Context, *BookReq) (*BookReply, error)
	CancelRPC(context.Context, *CancelReq) (*CancelReply, error)
}

// UnimplementedFlightsServer can be embedded to have forward compatible implementations.
type UnimplementedFlightsServer struct {
}

func (*UnimplementedFlightsServer) BookRPC(ctx context.Context, req *BookReq) (*BookReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookRPC not implemented")
}
func (*UnimplementedFlightsServer) CancelRPC(ctx context.Context, req *CancelReq) (*CancelReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelRPC not implemented")
}

func RegisterFlightsServer(s *grpc.Server, srv FlightsServer) {
	s.RegisterService(&_Flights_serviceDesc, srv)
}

func _Flights_BookRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightsServer).BookRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flights.Flights/BookRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightsServer).BookRPC(ctx, req.(*BookReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flights_CancelRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightsServer).CancelRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flights.Flights/CancelRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightsServer).CancelRPC(ctx, req.(*CancelReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Flights_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flights.Flights",
	HandlerType: (*FlightsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BookRPC",
			Handler:    _Flights_BookRPC_Handler,
		},
		{
			MethodName: "CancelRPC",
			Handler:    _Flights_CancelRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flights.proto",
}
