FROM golang:1.13.0-stretch

WORKDIR /go/src/github.com/triplewy/sagas

COPY . .

RUN go get -v -u ./...

RUN go build -o /bin/hotels-server cmd/hotels/main.go

EXPOSE 50051

ENTRYPOINT /bin/hotels-server