FROM golang:1.13.0-stretch

WORKDIR /build

COPY . .

RUN go get -u ./...

# Build for linux
ENV GOOS=linux
ENV GOARCH=amd64
ENV CGO_ENABLED=0 

RUN go build -o sagas cmd/sagas/main.go

ENTRYPOINT sagas