FROM golang:1.13.0-stretch

WORKDIR /go/src/github.com/triplewy/sagas

COPY . .

RUN go get -v -u ./...

RUN go build -o /bin/coordinator cmd/coordinator/main.go

EXPOSE 50051

ENTRYPOINT /bin/coordinator