// Code generated by protoc-gen-go. DO NOT EDIT.
// source: saga.proto

package sagas

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_NOT_REACHED Status = 0
	Status_START_T     Status = 1
	Status_END_T       Status = 2
	Status_START_C     Status = 3
	Status_END_C       Status = 4
	Status_ABORT       Status = 5
)

var Status_name = map[int32]string{
	0: "NOT_REACHED",
	1: "START_T",
	2: "END_T",
	3: "START_C",
	4: "END_C",
	5: "ABORT",
}

var Status_value = map[string]int32{
	"NOT_REACHED": 0,
	"START_T":     1,
	"END_T":       2,
	"START_C":     3,
	"END_C":       4,
	"ABORT":       5,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9818be635ac82bc9, []int{0}
}

type Vertex struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	T  *Func  `protobuf:"bytes,2,opt,name=t,proto3" json:"t,omitempty"`
	C  *Func  `protobuf:"bytes,3,opt,name=c,proto3" json:"c,omitempty"`
	// Transfer fields from Func t resp to Func c body
	TransferFields       []string `protobuf:"bytes,4,rep,name=transfer_fields,json=transferFields,proto3" json:"transfer_fields,omitempty"`
	Status               Status   `protobuf:"varint,5,opt,name=status,proto3,enum=sagas.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vertex) Reset()         { *m = Vertex{} }
func (m *Vertex) String() string { return proto.CompactTextString(m) }
func (*Vertex) ProtoMessage()    {}
func (*Vertex) Descriptor() ([]byte, []int) {
	return fileDescriptor_9818be635ac82bc9, []int{0}
}

func (m *Vertex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vertex.Unmarshal(m, b)
}
func (m *Vertex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vertex.Marshal(b, m, deterministic)
}
func (m *Vertex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vertex.Merge(m, src)
}
func (m *Vertex) XXX_Size() int {
	return xxx_messageInfo_Vertex.Size(m)
}
func (m *Vertex) XXX_DiscardUnknown() {
	xxx_messageInfo_Vertex.DiscardUnknown(m)
}

var xxx_messageInfo_Vertex proto.InternalMessageInfo

func (m *Vertex) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vertex) GetT() *Func {
	if m != nil {
		return m.T
	}
	return nil
}

func (m *Vertex) GetC() *Func {
	if m != nil {
		return m.C
	}
	return nil
}

func (m *Vertex) GetTransferFields() []string {
	if m != nil {
		return m.TransferFields
	}
	return nil
}

func (m *Vertex) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_NOT_REACHED
}

type Func struct {
	Url                  string            `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method               string            `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	RequestId            string            `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Body                 map[string]string `protobuf:"bytes,4,rep,name=body,proto3" json:"body,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Resp                 map[string]string `protobuf:"bytes,5,rep,name=resp,proto3" json:"resp,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Func) Reset()         { *m = Func{} }
func (m *Func) String() string { return proto.CompactTextString(m) }
func (*Func) ProtoMessage()    {}
func (*Func) Descriptor() ([]byte, []int) {
	return fileDescriptor_9818be635ac82bc9, []int{1}
}

func (m *Func) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Func.Unmarshal(m, b)
}
func (m *Func) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Func.Marshal(b, m, deterministic)
}
func (m *Func) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Func.Merge(m, src)
}
func (m *Func) XXX_Size() int {
	return xxx_messageInfo_Func.Size(m)
}
func (m *Func) XXX_DiscardUnknown() {
	xxx_messageInfo_Func.DiscardUnknown(m)
}

var xxx_messageInfo_Func proto.InternalMessageInfo

func (m *Func) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Func) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Func) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *Func) GetBody() map[string]string {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Func) GetResp() map[string]string {
	if m != nil {
		return m.Resp
	}
	return nil
}

type Edge struct {
	StartId string `protobuf:"bytes,1,opt,name=start_id,json=startId,proto3" json:"start_id,omitempty"`
	EndId   string `protobuf:"bytes,2,opt,name=end_id,json=endId,proto3" json:"end_id,omitempty"`
	// Transfer fields from start node resp to end node body
	TransferFields       []string `protobuf:"bytes,3,rep,name=transfer_fields,json=transferFields,proto3" json:"transfer_fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Edge) Reset()         { *m = Edge{} }
func (m *Edge) String() string { return proto.CompactTextString(m) }
func (*Edge) ProtoMessage()    {}
func (*Edge) Descriptor() ([]byte, []int) {
	return fileDescriptor_9818be635ac82bc9, []int{2}
}

func (m *Edge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Edge.Unmarshal(m, b)
}
func (m *Edge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Edge.Marshal(b, m, deterministic)
}
func (m *Edge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Edge.Merge(m, src)
}
func (m *Edge) XXX_Size() int {
	return xxx_messageInfo_Edge.Size(m)
}
func (m *Edge) XXX_DiscardUnknown() {
	xxx_messageInfo_Edge.DiscardUnknown(m)
}

var xxx_messageInfo_Edge proto.InternalMessageInfo

func (m *Edge) GetStartId() string {
	if m != nil {
		return m.StartId
	}
	return ""
}

func (m *Edge) GetEndId() string {
	if m != nil {
		return m.EndId
	}
	return ""
}

func (m *Edge) GetTransferFields() []string {
	if m != nil {
		return m.TransferFields
	}
	return nil
}

type SagaMsg struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vertices             map[string]*Vertex `protobuf:"bytes,2,rep,name=vertices,proto3" json:"vertices,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Edges                []*Edge            `protobuf:"bytes,3,rep,name=edges,proto3" json:"edges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SagaMsg) Reset()         { *m = SagaMsg{} }
func (m *SagaMsg) String() string { return proto.CompactTextString(m) }
func (*SagaMsg) ProtoMessage()    {}
func (*SagaMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_9818be635ac82bc9, []int{3}
}

func (m *SagaMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SagaMsg.Unmarshal(m, b)
}
func (m *SagaMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SagaMsg.Marshal(b, m, deterministic)
}
func (m *SagaMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SagaMsg.Merge(m, src)
}
func (m *SagaMsg) XXX_Size() int {
	return xxx_messageInfo_SagaMsg.Size(m)
}
func (m *SagaMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SagaMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SagaMsg proto.InternalMessageInfo

func (m *SagaMsg) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SagaMsg) GetVertices() map[string]*Vertex {
	if m != nil {
		return m.Vertices
	}
	return nil
}

func (m *SagaMsg) GetEdges() []*Edge {
	if m != nil {
		return m.Edges
	}
	return nil
}

func init() {
	proto.RegisterEnum("sagas.Status", Status_name, Status_value)
	proto.RegisterType((*Vertex)(nil), "sagas.Vertex")
	proto.RegisterType((*Func)(nil), "sagas.Func")
	proto.RegisterMapType((map[string]string)(nil), "sagas.Func.BodyEntry")
	proto.RegisterMapType((map[string]string)(nil), "sagas.Func.RespEntry")
	proto.RegisterType((*Edge)(nil), "sagas.Edge")
	proto.RegisterType((*SagaMsg)(nil), "sagas.SagaMsg")
	proto.RegisterMapType((map[string]*Vertex)(nil), "sagas.SagaMsg.VerticesEntry")
}

func init() { proto.RegisterFile("saga.proto", fileDescriptor_9818be635ac82bc9) }

var fileDescriptor_9818be635ac82bc9 = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0x69, 0x93, 0x2e, 0x2f, 0xac, 0x8b, 0x2c, 0x86, 0xb2, 0x0a, 0xa4, 0x52, 0x84, 0x28,
	0x1c, 0x72, 0x28, 0x07, 0x26, 0x24, 0x0e, 0x5d, 0x96, 0x89, 0x22, 0xb1, 0x21, 0x37, 0xda, 0x35,
	0xf2, 0x6a, 0x2f, 0x44, 0x2b, 0x49, 0xb1, 0x9d, 0x89, 0xfc, 0x12, 0x6e, 0xfc, 0x18, 0x7e, 0x19,
	0xb2, 0x93, 0x76, 0x1d, 0xeb, 0x85, 0x9b, 0xdf, 0xfb, 0xbe, 0xcf, 0xf9, 0xfc, 0xbd, 0x17, 0x00,
	0x49, 0x33, 0x1a, 0xae, 0x44, 0xa9, 0x4a, 0x6c, 0xeb, 0xb3, 0x1c, 0xfd, 0x46, 0xe0, 0x5c, 0x72,
	0xa1, 0xf8, 0x4f, 0xdc, 0x07, 0x2b, 0x67, 0x01, 0x1a, 0xa2, 0xb1, 0x4b, 0xac, 0x9c, 0xe1, 0x23,
	0x40, 0x2a, 0xb0, 0x86, 0x68, 0xec, 0x4d, 0xbc, 0xd0, 0xb0, 0xc3, 0xb3, 0xaa, 0x58, 0x10, 0xa4,
	0x34, 0xb4, 0x08, 0x3a, 0x3b, 0xa0, 0x05, 0x7e, 0x0d, 0x07, 0x4a, 0xd0, 0x42, 0x5e, 0x73, 0x91,
	0x5e, 0xe7, 0x7c, 0xc9, 0x64, 0xd0, 0x1d, 0x76, 0xc6, 0x2e, 0xe9, 0xaf, 0xdb, 0x67, 0xa6, 0x8b,
	0x5f, 0x81, 0x23, 0x15, 0x55, 0x95, 0x0c, 0xec, 0x21, 0x1a, 0xf7, 0x27, 0xfb, 0xed, 0x45, 0x73,
	0xd3, 0x24, 0x2d, 0x38, 0xfa, 0x65, 0x41, 0x57, 0xdf, 0x8d, 0x7d, 0xe8, 0x54, 0x62, 0xd9, 0xfa,
	0xd3, 0x47, 0xfc, 0x14, 0x9c, 0xef, 0x5c, 0x7d, 0x2b, 0x99, 0x71, 0xe9, 0x92, 0xb6, 0xc2, 0xcf,
	0x01, 0x04, 0xff, 0x51, 0x71, 0xa9, 0xd2, 0x9c, 0x19, 0x9b, 0x2e, 0x71, 0xdb, 0xce, 0x8c, 0xe1,
	0x37, 0xd0, 0xbd, 0x2a, 0x59, 0x6d, 0x6c, 0x79, 0x93, 0xc3, 0x2d, 0xff, 0xe1, 0x49, 0xc9, 0xea,
	0xb8, 0x50, 0xa2, 0x26, 0x86, 0xa2, 0xa9, 0x82, 0xcb, 0x55, 0x60, 0x3f, 0xa4, 0x12, 0x2e, 0x57,
	0x2d, 0x55, 0x53, 0x06, 0xef, 0xc1, 0xdd, 0xa8, 0xb5, 0xd7, 0x1b, 0x5e, 0xaf, 0xbd, 0xde, 0xf0,
	0x1a, 0x3f, 0x01, 0xfb, 0x96, 0x2e, 0x2b, 0xde, 0x5a, 0x6d, 0x8a, 0x0f, 0xd6, 0x31, 0xd2, 0xc2,
	0xcd, 0x5d, 0xff, 0x23, 0x1c, 0x51, 0xe8, 0xc6, 0x2c, 0xe3, 0xf8, 0x08, 0xf6, 0xa4, 0xa2, 0xc2,
	0x3c, 0xb6, 0x11, 0xf6, 0x4c, 0x3d, 0x63, 0xf8, 0x10, 0x1c, 0x5e, 0x30, 0x0d, 0xb4, 0x6a, 0x5e,
	0xb0, 0x19, 0xdb, 0x35, 0xa3, 0xce, 0xae, 0x19, 0x8d, 0xfe, 0x20, 0xe8, 0xcd, 0x69, 0x46, 0xbf,
	0xc8, 0xec, 0xc1, 0x7a, 0x1c, 0xc3, 0xde, 0x2d, 0x17, 0x2a, 0x5f, 0x70, 0x19, 0x58, 0x26, 0x9f,
	0x67, 0xeb, 0x09, 0x36, 0x8a, 0xf0, 0xb2, 0x85, 0x9b, 0x98, 0x36, 0x6c, 0xfc, 0x02, 0x6c, 0xce,
	0x32, 0xde, 0x7c, 0xf4, 0x6e, 0x83, 0xf4, 0x63, 0x48, 0x83, 0x0c, 0x3e, 0xc3, 0xfe, 0x3d, 0xf5,
	0x8e, 0x60, 0x5e, 0x6e, 0x07, 0xe3, 0x6d, 0xd6, 0xa7, 0x59, 0xe6, 0xad, 0x9c, 0xde, 0x26, 0xe0,
	0x34, 0x3b, 0x85, 0x0f, 0xc0, 0x3b, 0xbf, 0x48, 0x52, 0x12, 0x4f, 0xa3, 0x4f, 0xf1, 0xa9, 0xff,
	0x08, 0x7b, 0xd0, 0x9b, 0x27, 0x53, 0x92, 0xa4, 0x89, 0x8f, 0xb0, 0x0b, 0x76, 0x7c, 0x7e, 0x9a,
	0x26, 0xbe, 0x75, 0xd7, 0x8f, 0xfc, 0xce, 0xba, 0x1f, 0xf9, 0x5d, 0x7d, 0x9c, 0x9e, 0x5c, 0x90,
	0xc4, 0xb7, 0x27, 0x1f, 0xc1, 0x8b, 0xca, 0x52, 0xb0, 0xbc, 0xa0, 0xaa, 0x14, 0x38, 0x84, 0xc7,
	0x73, 0x1d, 0xba, 0x7e, 0x3b, 0xf9, 0x1a, 0xe1, 0xfe, 0xfd, 0x2c, 0x06, 0xff, 0xd4, 0x57, 0x8e,
	0xf9, 0x0b, 0xdf, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x04, 0xec, 0xef, 0xd8, 0x93, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CoordinatorClient is the client API for Coordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CoordinatorClient interface {
	StartSagaRPC(ctx context.Context, in *SagaMsg, opts ...grpc.CallOption) (*SagaMsg, error)
}

type coordinatorClient struct {
	cc *grpc.ClientConn
}

func NewCoordinatorClient(cc *grpc.ClientConn) CoordinatorClient {
	return &coordinatorClient{cc}
}

func (c *coordinatorClient) StartSagaRPC(ctx context.Context, in *SagaMsg, opts ...grpc.CallOption) (*SagaMsg, error) {
	out := new(SagaMsg)
	err := c.cc.Invoke(ctx, "/sagas.Coordinator/StartSagaRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServer is the server API for Coordinator service.
type CoordinatorServer interface {
	StartSagaRPC(context.Context, *SagaMsg) (*SagaMsg, error)
}

// UnimplementedCoordinatorServer can be embedded to have forward compatible implementations.
type UnimplementedCoordinatorServer struct {
}

func (*UnimplementedCoordinatorServer) StartSagaRPC(ctx context.Context, req *SagaMsg) (*SagaMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSagaRPC not implemented")
}

func RegisterCoordinatorServer(s *grpc.Server, srv CoordinatorServer) {
	s.RegisterService(&_Coordinator_serviceDesc, srv)
}

func _Coordinator_StartSagaRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SagaMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).StartSagaRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sagas.Coordinator/StartSagaRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).StartSagaRPC(ctx, req.(*SagaMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _Coordinator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sagas.Coordinator",
	HandlerType: (*CoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSagaRPC",
			Handler:    _Coordinator_StartSagaRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "saga.proto",
}
