// Code generated by protoc-gen-go. DO NOT EDIT.
// source: saga.proto

package sagas

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Vertex struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	T                    *Func    `protobuf:"bytes,2,opt,name=t,proto3" json:"t,omitempty"`
	C                    *Func    `protobuf:"bytes,3,opt,name=c,proto3" json:"c,omitempty"`
	TransferFields       []string `protobuf:"bytes,4,rep,name=transfer_fields,json=transferFields,proto3" json:"transfer_fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vertex) Reset()         { *m = Vertex{} }
func (m *Vertex) String() string { return proto.CompactTextString(m) }
func (*Vertex) ProtoMessage()    {}
func (*Vertex) Descriptor() ([]byte, []int) {
	return fileDescriptor_9818be635ac82bc9, []int{0}
}

func (m *Vertex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vertex.Unmarshal(m, b)
}
func (m *Vertex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vertex.Marshal(b, m, deterministic)
}
func (m *Vertex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vertex.Merge(m, src)
}
func (m *Vertex) XXX_Size() int {
	return xxx_messageInfo_Vertex.Size(m)
}
func (m *Vertex) XXX_DiscardUnknown() {
	xxx_messageInfo_Vertex.DiscardUnknown(m)
}

var xxx_messageInfo_Vertex proto.InternalMessageInfo

func (m *Vertex) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vertex) GetT() *Func {
	if m != nil {
		return m.T
	}
	return nil
}

func (m *Vertex) GetC() *Func {
	if m != nil {
		return m.C
	}
	return nil
}

func (m *Vertex) GetTransferFields() []string {
	if m != nil {
		return m.TransferFields
	}
	return nil
}

type Func struct {
	Url                  string            `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method               string            `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Body                 map[string]string `protobuf:"bytes,3,rep,name=body,proto3" json:"body,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Func) Reset()         { *m = Func{} }
func (m *Func) String() string { return proto.CompactTextString(m) }
func (*Func) ProtoMessage()    {}
func (*Func) Descriptor() ([]byte, []int) {
	return fileDescriptor_9818be635ac82bc9, []int{1}
}

func (m *Func) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Func.Unmarshal(m, b)
}
func (m *Func) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Func.Marshal(b, m, deterministic)
}
func (m *Func) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Func.Merge(m, src)
}
func (m *Func) XXX_Size() int {
	return xxx_messageInfo_Func.Size(m)
}
func (m *Func) XXX_DiscardUnknown() {
	xxx_messageInfo_Func.DiscardUnknown(m)
}

var xxx_messageInfo_Func proto.InternalMessageInfo

func (m *Func) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Func) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Func) GetBody() map[string]string {
	if m != nil {
		return m.Body
	}
	return nil
}

type Edge struct {
	StartId              string   `protobuf:"bytes,1,opt,name=start_id,json=startId,proto3" json:"start_id,omitempty"`
	EndId                string   `protobuf:"bytes,2,opt,name=end_id,json=endId,proto3" json:"end_id,omitempty"`
	TransferFields       []string `protobuf:"bytes,3,rep,name=transfer_fields,json=transferFields,proto3" json:"transfer_fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Edge) Reset()         { *m = Edge{} }
func (m *Edge) String() string { return proto.CompactTextString(m) }
func (*Edge) ProtoMessage()    {}
func (*Edge) Descriptor() ([]byte, []int) {
	return fileDescriptor_9818be635ac82bc9, []int{2}
}

func (m *Edge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Edge.Unmarshal(m, b)
}
func (m *Edge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Edge.Marshal(b, m, deterministic)
}
func (m *Edge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Edge.Merge(m, src)
}
func (m *Edge) XXX_Size() int {
	return xxx_messageInfo_Edge.Size(m)
}
func (m *Edge) XXX_DiscardUnknown() {
	xxx_messageInfo_Edge.DiscardUnknown(m)
}

var xxx_messageInfo_Edge proto.InternalMessageInfo

func (m *Edge) GetStartId() string {
	if m != nil {
		return m.StartId
	}
	return ""
}

func (m *Edge) GetEndId() string {
	if m != nil {
		return m.EndId
	}
	return ""
}

func (m *Edge) GetTransferFields() []string {
	if m != nil {
		return m.TransferFields
	}
	return nil
}

type SagaReq struct {
	Vertices             map[string]*Vertex `protobuf:"bytes,1,rep,name=vertices,proto3" json:"vertices,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Edges                []*Edge            `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SagaReq) Reset()         { *m = SagaReq{} }
func (m *SagaReq) String() string { return proto.CompactTextString(m) }
func (*SagaReq) ProtoMessage()    {}
func (*SagaReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9818be635ac82bc9, []int{3}
}

func (m *SagaReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SagaReq.Unmarshal(m, b)
}
func (m *SagaReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SagaReq.Marshal(b, m, deterministic)
}
func (m *SagaReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SagaReq.Merge(m, src)
}
func (m *SagaReq) XXX_Size() int {
	return xxx_messageInfo_SagaReq.Size(m)
}
func (m *SagaReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SagaReq.DiscardUnknown(m)
}

var xxx_messageInfo_SagaReq proto.InternalMessageInfo

func (m *SagaReq) GetVertices() map[string]*Vertex {
	if m != nil {
		return m.Vertices
	}
	return nil
}

func (m *SagaReq) GetEdges() []*Edge {
	if m != nil {
		return m.Edges
	}
	return nil
}

type SagaResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SagaResp) Reset()         { *m = SagaResp{} }
func (m *SagaResp) String() string { return proto.CompactTextString(m) }
func (*SagaResp) ProtoMessage()    {}
func (*SagaResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9818be635ac82bc9, []int{4}
}

func (m *SagaResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SagaResp.Unmarshal(m, b)
}
func (m *SagaResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SagaResp.Marshal(b, m, deterministic)
}
func (m *SagaResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SagaResp.Merge(m, src)
}
func (m *SagaResp) XXX_Size() int {
	return xxx_messageInfo_SagaResp.Size(m)
}
func (m *SagaResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SagaResp.DiscardUnknown(m)
}

var xxx_messageInfo_SagaResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Vertex)(nil), "sagas.Vertex")
	proto.RegisterType((*Func)(nil), "sagas.Func")
	proto.RegisterMapType((map[string]string)(nil), "sagas.Func.BodyEntry")
	proto.RegisterType((*Edge)(nil), "sagas.Edge")
	proto.RegisterType((*SagaReq)(nil), "sagas.SagaReq")
	proto.RegisterMapType((map[string]*Vertex)(nil), "sagas.SagaReq.VerticesEntry")
	proto.RegisterType((*SagaResp)(nil), "sagas.SagaResp")
}

func init() { proto.RegisterFile("saga.proto", fileDescriptor_9818be635ac82bc9) }

var fileDescriptor_9818be635ac82bc9 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xc1, 0x8e, 0xd3, 0x30,
	0x14, 0x94, 0x93, 0x34, 0xdb, 0xbc, 0xb0, 0x5d, 0x64, 0xb1, 0x28, 0x5b, 0x71, 0x08, 0xe5, 0x40,
	0xb8, 0x04, 0x29, 0x1c, 0x58, 0x71, 0xe0, 0xc0, 0x6a, 0x57, 0x5a, 0x4e, 0x28, 0x2b, 0xf5, 0x5a,
	0xb9, 0xf1, 0x6b, 0x88, 0x5a, 0xe2, 0x62, 0xbb, 0x85, 0xfc, 0x07, 0x5f, 0xc2, 0x17, 0xae, 0xec,
	0xb8, 0x55, 0x2b, 0xe5, 0xe6, 0xf7, 0x66, 0x26, 0xe3, 0x99, 0x18, 0x40, 0xb1, 0x9a, 0xe5, 0x5b,
	0x29, 0xb4, 0xa0, 0x23, 0x73, 0x56, 0xb3, 0x3f, 0x10, 0xce, 0x51, 0x6a, 0xfc, 0x4b, 0x27, 0xe0,
	0x35, 0x3c, 0x21, 0x29, 0xc9, 0xa2, 0xd2, 0x6b, 0x38, 0xbd, 0x01, 0xa2, 0x13, 0x2f, 0x25, 0x59,
	0x5c, 0xc4, 0xb9, 0x25, 0xe7, 0x0f, 0xbb, 0xb6, 0x2a, 0x89, 0x36, 0x50, 0x95, 0xf8, 0x03, 0x50,
	0x45, 0xdf, 0xc3, 0x95, 0x96, 0xac, 0x55, 0x2b, 0x94, 0x8b, 0x55, 0x83, 0x1b, 0xae, 0x92, 0x20,
	0xf5, 0xb3, 0xa8, 0x9c, 0x1c, 0xd6, 0x0f, 0x76, 0x3b, 0xfb, 0x47, 0x20, 0x30, 0x22, 0xfa, 0x12,
	0xfc, 0x9d, 0xdc, 0x38, 0x63, 0x73, 0xa4, 0xaf, 0x21, 0xfc, 0x85, 0xfa, 0xa7, 0xe0, 0xd6, 0x3e,
	0x2a, 0xdd, 0x44, 0x3f, 0x40, 0xb0, 0x14, 0xbc, 0x4b, 0xfc, 0xd4, 0xcf, 0xe2, 0xe2, 0xfa, 0xc4,
	0x39, 0xff, 0x26, 0x78, 0x77, 0xdf, 0x6a, 0xd9, 0x95, 0x96, 0x32, 0xfd, 0x0c, 0xd1, 0x71, 0x65,
	0x1c, 0xd6, 0xd8, 0x1d, 0x1c, 0xd6, 0xd8, 0xd1, 0x57, 0x30, 0xda, 0xb3, 0xcd, 0x0e, 0x9d, 0x41,
	0x3f, 0x7c, 0xf1, 0x6e, 0xc9, 0x8c, 0x41, 0x70, 0xcf, 0x6b, 0xa4, 0x37, 0x30, 0x56, 0x9a, 0x49,
	0xbd, 0x38, 0x76, 0x72, 0x61, 0xe7, 0x47, 0x4e, 0xaf, 0x21, 0xc4, 0x96, 0x1b, 0xc0, 0xa9, 0xb1,
	0xe5, 0x8f, 0x7c, 0x28, 0xb9, 0x3f, 0x98, 0xfc, 0x3f, 0x81, 0x8b, 0x27, 0x56, 0xb3, 0x12, 0x7f,
	0xd3, 0x5b, 0x18, 0xef, 0x51, 0xea, 0xa6, 0x42, 0x95, 0x10, 0x1b, 0xeb, 0x8d, 0x8b, 0xe5, 0x18,
	0xf9, 0xdc, 0xc1, 0x7d, 0xba, 0x23, 0x9b, 0xbe, 0x85, 0x11, 0xf2, 0x1a, 0x55, 0xe2, 0x59, 0xd9,
	0xe1, 0x3f, 0x98, 0xcb, 0x97, 0x3d, 0x32, 0xfd, 0x0e, 0x97, 0x67, 0xea, 0x81, 0x22, 0xde, 0x9d,
	0x16, 0x11, 0x17, 0x97, 0xee, 0x2b, 0xfd, 0x93, 0x38, 0xed, 0x05, 0x60, 0xdc, 0xdf, 0x48, 0x6d,
	0x8b, 0xaf, 0x10, 0xdf, 0x09, 0x21, 0x79, 0xd3, 0x32, 0x2d, 0x24, 0xfd, 0x08, 0x2f, 0x9e, 0x4c,
	0x35, 0x16, 0xff, 0x71, 0x47, 0x27, 0xe7, 0x09, 0xa6, 0x57, 0x67, 0xb3, 0xda, 0x2e, 0x43, 0xfb,
	0x02, 0x3f, 0x3d, 0x07, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xf4, 0xa8, 0x63, 0x8f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CoordinatorClient is the client API for Coordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CoordinatorClient interface {
	StartSagaRPC(ctx context.Context, in *SagaReq, opts ...grpc.CallOption) (*SagaResp, error)
}

type coordinatorClient struct {
	cc *grpc.ClientConn
}

func NewCoordinatorClient(cc *grpc.ClientConn) CoordinatorClient {
	return &coordinatorClient{cc}
}

func (c *coordinatorClient) StartSagaRPC(ctx context.Context, in *SagaReq, opts ...grpc.CallOption) (*SagaResp, error) {
	out := new(SagaResp)
	err := c.cc.Invoke(ctx, "/sagas.Coordinator/StartSagaRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServer is the server API for Coordinator service.
type CoordinatorServer interface {
	StartSagaRPC(context.Context, *SagaReq) (*SagaResp, error)
}

// UnimplementedCoordinatorServer can be embedded to have forward compatible implementations.
type UnimplementedCoordinatorServer struct {
}

func (*UnimplementedCoordinatorServer) StartSagaRPC(ctx context.Context, req *SagaReq) (*SagaResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSagaRPC not implemented")
}

func RegisterCoordinatorServer(s *grpc.Server, srv CoordinatorServer) {
	s.RegisterService(&_Coordinator_serviceDesc, srv)
}

func _Coordinator_StartSagaRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SagaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).StartSagaRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sagas.Coordinator/StartSagaRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).StartSagaRPC(ctx, req.(*SagaReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Coordinator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sagas.Coordinator",
	HandlerType: (*CoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSagaRPC",
			Handler:    _Coordinator_StartSagaRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "saga.proto",
}
