// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeter.proto

package greeter

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GreetReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetReq) Reset()         { *m = GreetReq{} }
func (m *GreetReq) String() string { return proto.CompactTextString(m) }
func (*GreetReq) ProtoMessage()    {}
func (*GreetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{0}
}

func (m *GreetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetReq.Unmarshal(m, b)
}
func (m *GreetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetReq.Marshal(b, m, deterministic)
}
func (m *GreetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetReq.Merge(m, src)
}
func (m *GreetReq) XXX_Size() int {
	return xxx_messageInfo_GreetReq.Size(m)
}
func (m *GreetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetReq.DiscardUnknown(m)
}

var xxx_messageInfo_GreetReq proto.InternalMessageInfo

type GreetReply struct {
	Reply                string   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetReply) Reset()         { *m = GreetReply{} }
func (m *GreetReply) String() string { return proto.CompactTextString(m) }
func (*GreetReply) ProtoMessage()    {}
func (*GreetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{1}
}

func (m *GreetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetReply.Unmarshal(m, b)
}
func (m *GreetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetReply.Marshal(b, m, deterministic)
}
func (m *GreetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetReply.Merge(m, src)
}
func (m *GreetReply) XXX_Size() int {
	return xxx_messageInfo_GreetReply.Size(m)
}
func (m *GreetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetReply.DiscardUnknown(m)
}

var xxx_messageInfo_GreetReply proto.InternalMessageInfo

func (m *GreetReply) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func init() {
	proto.RegisterType((*GreetReq)(nil), "greeter.GreetReq")
	proto.RegisterType((*GreetReply)(nil), "greeter.GreetReply")
}

func init() { proto.RegisterFile("greeter.proto", fileDescriptor_e585294ab3f34af5) }

var fileDescriptor_e585294ab3f34af5 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2f, 0x4a, 0x4d,
	0x2d, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0xa5, 0x64, 0xd2,
	0xf3, 0xf3, 0xd3, 0x73, 0x52, 0xf5, 0x13, 0x0b, 0x32, 0xf5, 0x13, 0xf3, 0xf2, 0xf2, 0x4b, 0x12,
	0x4b, 0x32, 0xf3, 0xf3, 0x8a, 0x21, 0xca, 0x94, 0xb8, 0xb8, 0x38, 0xdc, 0x41, 0x0a, 0x83, 0x52,
	0x0b, 0x95, 0x94, 0xb8, 0xb8, 0xa0, 0xec, 0x82, 0x9c, 0x4a, 0x21, 0x11, 0x2e, 0xd6, 0x22, 0x10,
	0x43, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc2, 0x31, 0xf2, 0xe5, 0x62, 0x77, 0x87, 0x18,
	0x2c, 0xe4, 0x04, 0xd3, 0x1a, 0xe0, 0x2c, 0x24, 0xa8, 0x07, 0xb3, 0x1d, 0x66, 0x9a, 0x94, 0x30,
	0xba, 0x50, 0x41, 0x4e, 0xa5, 0x12, 0x5f, 0xd3, 0xe5, 0x27, 0x93, 0x99, 0x38, 0x84, 0xd8, 0xf4,
	0xc1, 0x92, 0x49, 0x6c, 0x60, 0x57, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x17, 0x5a, 0x58,
	0xd5, 0xbd, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	GreetRPC(ctx context.Context, in *GreetReq, opts ...grpc.CallOption) (*GreetReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) GreetRPC(ctx context.Context, in *GreetReq, opts ...grpc.CallOption) (*GreetReply, error) {
	out := new(GreetReply)
	err := c.cc.Invoke(ctx, "/greeter.Greeter/GreetRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	GreetRPC(context.Context, *GreetReq) (*GreetReply, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) GreetRPC(ctx context.Context, req *GreetReq) (*GreetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GreetRPC not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_GreetRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GreetRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greeter.Greeter/GreetRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GreetRPC(ctx, req.(*GreetReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greeter.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GreetRPC",
			Handler:    _Greeter_GreetRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greeter.proto",
}
